version: "3.8"
services:
  # Redis
  redis:
    image: redis
    container_name: redis
    volumes:
      - ../redis_data:/data
    expose:
      - 6379

  # Database Postgres
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    container_name: postgres_db
    ports:
      - "5432:5432"
